server:
  error:
    include-stacktrace: ALWAYS
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Shop
    username: postgres
    password: andrew
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-dev.xml
liquibase:


spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false