server:
  error:
    include-stacktrace: ALWAYS
spring:
 datasource:
   url: jdbc:postgresql://postgres:5432/Shop
   username: postgres
   password: ${POSTGRES_PASSWORD}
   driver-class-name: org.postgresql.Driver
 jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
     ddl-auto: none
liquibase:
 change-log: classpath:/db/changelog/changelog-dev.xml