server:
  port:  8090
  error:
    include-stacktrace: ALWAYS
spring:
  datasource:
    url: jdbc:h2:mem:dev
    platform: h2
    initialize: true
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-dev.xml
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000